name: Master branch workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Automated build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install & check dependencies
        run: 
          npm run ci:deps:install 
          # && 
          # npm run ci:deps:audit

      #- name: check code quality
      #  run: 
      #    npm run ci:check:code

      #- name: test
      #  run: 
      #    npm run ci:test:unit && 
      #    npm run ci:test:integration && 
      #    npm run ci:test:e2e

      - name: build & pack
        run:
          npm run ci:build && npm run ci:dist
          

      - name: release package
        run:
          npm run ci:release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: LGV
        run:
          ls -ltr ./dist
          
      #- name: LGV2
      #  run:
      #    ./kk.exe
      
      #- name: LGV3
      #  run:
      #    cat ./cheese.log
